name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Build
        run: |
          cd init && go build -a -o bin/init && cd ..
          cd k8s-health && go build -a -o bin/k8s-health && cd ..
          cd lock && go build -a -o bin/lock && cd ..
          cd hashi-health && go build -a -o bin/hashi-health && cd ..

      - name: Test
        run: |
          cd init && go test -cover -v ./... && cd ..
          cd k8s-health && go test -cover -v ./... && cd ..
          cd lock && go test -cover -v ./... && cd ..
          cd hashi-health && go test -cover -v ./... && cd ..
